-- require("mini.animate").setup()
require("mini.surround").setup()
require("mini.pairs").setup()
require("mini.hipatterns").setup()
require("mini.statusline").setup()
require("mini.trailspace").setup()
